### ISSUE TITLE
Need more confirmation of resent invitations.

### ISSUE THREAD

**Issue by somexpert** [unt-libraries/django-invite#35]
Currently the datetime of the resent invitation does not change, nor is there any big indicator that the invitation actually got resent. The only indicators are a change in the URL and a very small message at the bottom of the open invitations. We should make it clear that the invitation was resent.

**Comment by ldko** [comment]
@madhulika95b can you check if this is still an issue that needs addressing, and if so, clear it up?

**Comment by somexpert** [comment]
This was addressed in #67
