### ISSUE TITLE
Server error at amnesia

### ISSUE THREAD

**Issue by ldko** [unt-libraries/django-invite#46]
If a user tries to get a reset password email by entering their email address via the `amnesia` view, if the [email address belongs to multiple users in the system](https://github.com/unt-libraries/django-invite/blob/e83adfadb8313a52ac849dc93b96c26e82b83027/invite/views.py#L98) (as far as I looked it is not a unique field), an exception is thrown resulting in a server error. We should perhaps make the email field unique and/or catch an exception and tell the user to contact someone for assistance. Example exception:
```
Internal Server Error: /accounts/amnesia/

MultipleObjectsReturned at /accounts/amnesia/
get() returned more than one User -- it returned 2!

```

**Comment by madhulika95b** [comment]
Do we also want to make `username` a unique field along with `email` ?

**Comment by ldko** [comment]
Oops, my initially suggested solution doesn't make sense. We shouldn't be looking at email being unique in `invite.models.InviteItem`. The `invite.forms` module already does checking for email and username uniqueness against the existing users in django auth. Instead we could do a `filter` instead of a `get` and use the first item in the queryset (usually there should only be one) unless we created multiple accounts for someone directly making use of django admin. Does that make sense?
